# Conclusion
\setlength{\parskip}{2em}

My dissertation focuses on integrating data and models with an informed understanding of pathogen biology and ecology to inform the control and elimination of canine rabies. In Chapter 2, I established a surveillance study of canine rabies in the Moramanga District, Madagascar to evaluate surveillance and burden of rabies. I find that poor surveillance masks high burden of human deaths and exposures and the continuous endemic circulation of canine rabies. The clinic-based investigation tools developed in this study could be usefully applied at a larger scale and in more settings to improve surveillance. In Chapter 3, I integrate this finer scale, comprehensive data, with broader scale, messy routine public health data, and develop statistical models that can integrate these data across scales to estimate the impact of geographic access to PEP on shaping rabies burden in Madagascar, and how expanding access to PEP can reduce this burden. I find that even given ideal expansion of PEP to all major health centers in Madagascar, that a substantial number of deaths will still occur due to the landscape of care. This work also highlights how using data naively without considering its biases in representation can skew estimates of burden and outcomes. I use two case studies to highlight that while access to this life-saving vaccine should be a matter of equity, that predicting human behavior and care seeking is challenging and that even in best case scenarios PEP alone will like not be able to eliminate deaths due to canine rabies. 

In Chapter 4, I review the existing body of mathematical modeling studies for canine rabies, and point out key gaps both methodologically and in terms of data. I find that existing models of canine rabies generally fail to capture endemic and epidemic disease dynamics, and that few modeling studies use data to fit their models, largely due to the lack of high quality routine surveillance data available. Finally in Chapter 5, I work to address these gaps by using simulation-based inference to fit individual-based model to a rich dataset on canine rabies cases and domestic dog populations in the Serengeti District, Tanzania. I find that integrating both the spatial scale of control and of population mixing is key to predicting observed dynamics and expectations of endemic diseases. Incorporating this understanding into strategies for control, i.e. focusing on spatial as well as temporal coverage targets or coordinating vaccination or surveillance efforts across larger geographic scales, could improve control prospects. 

## Future directions
Overall, my work highlights how integrating models and data can allow us to bound our expectations for transmission and disease outcomes. Moving forward methodologically in terms of dynamic modeling of canine rabies, integrating other data streams such as phylogenetic data into epidemiological models could shed light on the scale of maintenance for canine rabies [@brunker2018; @bourhy2016; @dellicour2017]. Further work is needed to explore the impact that larger scale spatial and landscape structure may have on canine rabies dynamics. While the individual based model I developed was simplified to implicitly capture many aspects of rabies transmission, this modeling and inference framework relies on high resolution population and case data. Ultimately, developing approximations for key aspects of transmission that can be captured implicitly (such as the scale of mixing) without needing explicit data to parameterize them, could be key to adoption of improved modeling frameworks that align with observed dynamics. More broadly, this work mirrors many of the pressing issues facing infectious disease modelers: 1) How do we balance complexity and tractability of models; 2) How do we integrate noisy and incomplete data into quantitative modeling approaches and quantify the uncertainty appropriately; 3) How do we use statistical methods to make inferences from these imperfect models and data [@funk2020; @park2020]. This work also highlights emergent issues in control and elimination, such as the importance of social and spatial heterogeneities in vaccination coverage [@takahashi2017], the development of improved coverage targets based on the disease specific context [@funk2019], and the role of connectivity in promoting persistence of infectious diseases across large scales [@kraemer2018.

## Policy Reccommendations
Overall, my work contributes many practical recommendations to how to improve rabies surveillance and control programs. In addition to the work presented here, the field work in Madagascar resulted in two other policy relevant outputs: 1) a comparison of filter paper as a diagnostic tool to increase sampling in remote areas and 2) a comparison of pilot vaccination campaigns and modeling of alternative community based vaccination strategies in the Moramanga District (see Appendix for full abstracts). These studies point to the importance of accounting for the context specific challenges, which in Madagascar are largely inequalities spatially in access to care and services. The work in Chapter 3 builds on this knowledge and develops new methods for analyzing bite patient data that attempt to account for who is not represented in this data. This approach could be applied to other settings to prioritize areas or groups where PEP expansion could be targeted. Chapter 3 also highlights that even though ZeroBy30 is technically a goal to eliminate burden of deaths rather than transmission, without dog vaccination it is unlikely that we will achieve even the former. In that vein, improving surveillance generally and increasing the availability of representative and routine datasets is likely the most important aspect of canine rabies research programs that should be implemented alongside vaccination programs. Without improvements in surveillance, we will not be able to evaluate whether much of the insights generated by this research, such as using expanding PEP access or implementing community based vaccination, are effective at controlling rabies transmission and reducing human deaths. Chapter 2 and much recent work develops toolsets to do so, focusing on strategies that build on top of existing health care systems and understandings of rabies epidemiology (broadly classified as Integrated Bite Case Management, [@undurraga2017; @Lushasi2020]).

Ultimately, we have the tools to end deaths due to canine rabies globally. Rabies control in dogs and PEP access for humans should be viewed as a public good, and the largest barriers to it's control are global and within country inequities in the availability of care for humans and animals. While, data and models are useful tools to inform control and elimination strategies, they are not a silver bullet. Interdisciplinary approaches that engage with the political and social realities of disease control, and that move beyond technocratic solutions will be needed to push the world to ZeroBy30. 

## References
\setlength{\parskip}{1em}

::: {#refs_conc}
:::
