# Appendix: Additional publications and software resulting from dissertation work {-}

## Additional publications {-}
\setlength{\parskip}{2em}

1. Filla C, **Rajeev M[^1]**, Randriana Z, et al. Lessons learned and paths forward for rabies dog vaccination in Madagascar: a case study of pilot vaccination campaigns in Moramanga District. Accepted in Tropical Medicine and Infectious Diseases.  
_**Abstract:** Canine rabies causes an estimated 60,000 human deaths per year, but these deaths are preventable through post-exposure prophylaxis of people and  vaccination of domestic dogs. Dog vaccination campaigns targeting 70% of the population are effective at interrupting transmission. Here, we report on lessons learned during pilot dog vaccination campaigns in the Moramanga District of Madagascar. We compare two different vaccination strategies: a volunteer driven effort to vaccinate dogs in two communes using static point vaccination, and continuous vaccination as part of routine veterinary services. We used dog age data from the campaigns to estimate key demographic parameters and to simulate different vaccination strategies. Overall, we found that dog vaccination was feasible and that most dogs were accessible to vaccination. The static-point campaign achieved higher coverage, but required more resources and had a limited geographic scope compared to the continuous delivery campaign. Our modeling results suggest that targeting puppies through community-based vaccination efforts could improve coverage. We found that mass dog vaccination is feasible and can achieve high coverage in Madagascar, however context-specific strategies and an investment in dog vaccination as a public good will be required to move the country towards elimination._

2. Rasolonjatovo FS, Guis H, **Rajeev M**, Dacheux L, Nomenjanahary LA, Razafitrimo G, ... & Andriamandimby SF. (2020). Enabling animal rabies diagnostic in low-access areas: Sensitivity and specificity of a molecular diagnostic test from cerebral tissue dried on filter paper. PLoS Neglected Tropical Diseases, 14(3), e0008116.  
_**Abstract:** Rabies is a lethal zoonotic encephalomyelitis that causes an estimated 59,000 human deaths yearly worldwide. Although developing countries of Asia and Africa bear the heaviest burden, surveillance and disease detection in these countries is often hampered by the absence of local laboratories able to diagnose rabies and/or the difficulties of sample shipment from low-access areas to national reference laboratories. Filter papers offer a convenient cost-effective alternative for the sampling, shipment, and storage of biological materials for the diagnosis of many pathogens including rabies virus, yet the properties of diagnostic tests using this support have not been evaluated thoroughly. Sensitivity and specificity of molecular diagnosis of rabies infection using a reverse transcription followed by a hemi-nested polymerase chain reaction (RT-hn-PCR) either directly on brain tissue or using brain tissue dried on filter paper were assessed on 113 suspected field animal samples in comparison to the direct fluorescent antibody test (FAT) recommended by the World Health Organization as one of the reference tests for rabies diagnosis. Impact of the duration of the storage was also evaluated. The sensitivity and the specificity of RT-hn-PCR i) on brain tissue were 96.6% (95% CI: [88.1–99.6]) and 92.7% (95% CI: [82.4–98.0]) respectively and ii) on brain tissue dried on filter paper 100% (95% CI: [93.8–100.0]) and 90.9% (95% CI: [80.0–97.0]) respectively. No loss of sensitivity of RT-hn-PCR on samples of brain tissue dried on filter paper left 7 days at ambient temperature was detected indicating that this method would enable analyzing impregnated filter papers sent to the national reference laboratory at ambient temperature within a 1-week shipment time. It could therefore be an effective alternative to facilitate storage and shipment of samples from low-access areas to enhance and expand rabies surveillance._

3. **WHO Rabies Modeling Consortium[^2]** (2019). The potential effect of improved provision of rabies post-exposure prophylaxis in Gavi-eligible countries: a modelling study. The Lancet Infectious Diseases, 19(1), 102-111.  
_**Abstract:** Tens of thousands of people die from dog-mediated rabies annually. Deaths can be prevented through post-exposure prophylaxis for people who have been bitten, and the disease eliminated through dog vaccination. Current post-exposure prophylaxis use saves many lives, but availability remains poor in many rabies-endemic countries due to high costs, poor access, and supply. We developed epidemiological and economic models to investigate the effect of an investment in post-exposure prophylaxis by Gavi, the Vaccine Alliance. We modelled post-exposure prophylaxis use according to the status quo, with improved access using WHO-recommended intradermal vaccination, with and without rabies immunoglobulin, and with and without dog vaccination. We took the health provider perspective, including only direct costs. We predict more than 1 million deaths will occur in the 67 rabies-endemic countries considered from 2020 to 2035, under the status quo. Current post-exposure prophylaxis use prevents approximately 56,000 deaths annually. Expanded access to, and free provision of, post-exposure prophylaxis would prevent an additional 489,000 deaths between 2020 and 2035. Under this switch to efficient intradermal post-exposure prophylaxis regimens, total projected vaccine needs remain similar (about 73 million vials) yet 17·4 million more people are vaccinated, making this an extremely cost-effective method, with costs of US 635 per death averted and 33 per disability-adjusted life-years averted. Scaling up dog vaccination programmes could eliminate dog-mediated rabies over this time period; improved post-exposure prophylaxis access remains cost-effective under this scenario, especially in combination with patient risk assessments to reduce unnecessary post-exposure prophylaxis use. Investing in post-exposure vaccines would be an extremely cost-effective intervention that could substantially reduce disease burden and catalyse dog vaccination efforts to eliminate dog-mediated rabies._

4. Sreenivasan N, **Working group on Rabies PEP logistics[^3]** (2019). Overview of rabies post-exposure prophylaxis access, procurement and distribution in selected countries in Asia and Africa, 2017–2018. Vaccine, 37, A6-A13.  
_**Abstract:** Rabies is a neglected zoonotic disease with a global burden of approximately 59,000 human deaths a year. Once clinical symptoms appear, rabies is almost invariably fatal; however, with timely and appropriate post-exposure prophylaxis (PEP) consisting of wound washing, vaccine, and in some cases rabies immunoglobulin (RIG), the disease is almost entirely preventable. Access to PEP is limited in many countries, and when available, is often very expensive. We distributed a standardized assessment tool electronically to a convenience sample of 25 low- and middle-income countries in Asia and Africa to collect information on rabies PEP procurement, forecasting, distribution, monitoring and reporting. Information was collected from national rabies focal points, focal points at the World Health Organization (WHO) country offices, and others involved in procurement, logistics and distribution of PEP. Because RIG was limited in availability or unavailable in many countries, the assessment focused on vaccine. Data were collected between January 2017 and May 2018. We received responses from key informants in 23 countries: 11 countries in Asia and 12 countries in Africa. In 9 of 23 (39%) countries, rabies vaccine was provided for free in the public sector and was consistently available. In 10 (43%) countries, all or some patients were required to pay for the vaccine in the public sector, with the cost of a single dose ranging from US$ 6.60 to US$ 20/dose. The primary reason for the high cost of the vaccine for patients was a lack of funding at the central level to subsidize vaccine costs. In the remaining 4 (17%) countries, vaccine was provided for free but was often unavailable so patients were required to purchase it instead. The majority of countries used the intramuscular route for vaccine administration and only 5 countries exclusively used the dose-sparing intradermal (ID) route. Half (11/22; 50%) of all countries assessed had a standardized distribution system for PEP, separate from the systems used for routine childhood vaccines, and almost half used separate storage facilities at both central and health facility levels. Approximately half (9/22; 41%) of all countries assessed reported having regular weekly, monthly or quarterly reporting on rabies vaccination. While all countries in our assessment had rabies vaccines available in the public sector to some extent, barriers to access include the high cost of the vaccine to the government as well as to patients. Countries should be encouraged to use ID administration as this would provide access to rabies vaccine for many more people with the same number of vaccine vials. In addition, standardized monitoring and reporting of vaccine utilization should be encouraged, in order to improve data on PEP needs._


## Additional software {-}

1. **`popcompr`:** An R package to aid in comparing high resolution population datasets for humanitarian and research purposes. Available at https://github.com/mrajeev08/popcompr.

2. **`simrabid`:** An R package to simulate an individual based model of rabies transmission. Available at https://github.com/mrajeev08/simrabid.

3. **`subutil`:** A command line utility tool to send and schedule R scripts to run on the Princeton Research Computing clusters and pull down results when finished. Available at https://github.com/mrajeev08/subutil.

[^1]: Shared co-first authorship.
[^2]: Member of consortium.
[^3]: Member of working group.